### ISSUE TITLE
Translate docs to English

### ISSUE THREAD

**Issue by Prog-in** [Prog-in/PatMail#1]
TODO: Translate docs to english (and to another languages too, if possible).

**Comment by KrownWealth** [comment]
I would love to work on this issue, translate from Portuguese to five other different languages including English.

**Comment by Prog-in** [comment]
> I would love to work on this issue, translate from Portuguese to five other different languages including English.

I would appreciate your work!

**Comment by KrownWealth** [comment]
Kindly assign the issue to me, so I can start working on it.

**Comment by Prog-in** [comment]
> Kindly assign the issue to me, so I can start working on it.

Oh, of course.

**Comment by KrownWealth** [comment]
I've started working on the issue

**Comment by KrownWealth** [comment]
I can see the english translation has been worked on by somebody else. Nevertheless I still wish to contribute, can I have other languages you want the readme be translated into?

And can I encalpsulate the translations into a folder for uniformity?

**Comment by Prog-in** [comment]
> I can see the issue has been worked on by somebody else.

Yes, but only for English. If you want, I can close this question and open another one specifically for languages other than English.

**Comment by Prog-in** [comment]
> I can see the english translation has been worked on by somebody else. Nevertheless I still wish to contribute, can I have other languages you want the readme be translated into?
> 
> And can I encalpsulate the translations into a folder for uniformity?

Yes, of course! Would be nice

**Comment by KrownWealth** [comment]
Thanks for having me work on the documentation, it's a great privilege.

One thing more, I was checking the README.md file some minutes ago and I noticed a link error. 

Since the issue is now closed I can't push the correct changes I made, it would be better if you correct it from you end or what do you think?

**Comment by Prog-in** [comment]
Fixed!
